### ISSUE TITLE
tutorial error

### ISSUE THREAD

**Issue by am821** [larssnip/micropan#5]
Hi, following the tutorial I encountered this error and am wondering how to fix it? Thanks
for(i in 1:nrow(gnm.tbl)){
+   panPrep(file.path("tmp", str_c(gnm.tbl$GenBank_ID[i], ".faa")),
+           gnm.tbl$GID.tag[i],
+           file.path("faa", str_c(gnm.tbl$GenBank_ID[i], ".faa")))
+ }
Error: Column `Header` must be length 0 (the number of rows) or one, not 2

**Comment by larssnip** [comment]
Hi,


I am not capable of reproducing this error, but it could be due to an error in the readFasta-function of the microseq package. This has been corrected, and has been uploaded to CRAN, but it takes some days before it is available. I enclose the latest version of both packages here, but they will soon be available on CRAN as well. Please let me know if this helps.


LS

**Comment by am821** [comment]
Thank you for the swift reply!
sorry where are the latest versions of both packages enclosed? 
Thank you!

**Comment by larssnip** [comment]
Well, I tried to attach them but since they are tar archives they may have been discarded by the spam filter.

You can install from GitHub. First, make certain you have the devtools package installed (from CRAN). Then

devtools::install_github("larssnip/microseq")

…should do the trick. Then repeat it for micropan.


LS

**Comment by am821** [comment]
Still not working and I think the issue might actually be earlier in the code

for(i in 1:nrow(gnm.tbl)){
  genome <- readFasta(file.path("rawdata", str_c(gnm.tbl$GenBank_ID[i], "_genomic.fna"))) # for use below
  findGenes(file.path("rawdata", str_c(gnm.tbl$GenBank_ID[i], "_genomic.fna"))) %>% 
  filter(Score > 40) %>% 
  gff2fasta(genome) %>% 
  mutate(Sequence = translate(Sequence)) %>% 
  writeFasta(file.path("tmp", str_c(gnm.tbl$GenBank_ID[i], ".faa")))
}
ive attached the outputs from this command as images
thanks again!
![Screenshot from 2020-06-04 13-06-16](https://user-images.githubusercontent.com/66393783/83754841-88c87380-a664-11ea-88dd-56688612cb8d.png)
![Screenshot from 2020-06-04 13-06-42](https://user-images.githubusercontent.com/66393783/83754851-8b2acd80-a664-11ea-8125-0ed36830fdcb.png)

**Comment by am821** [comment]
Nevermind it is working now thank you for the help!

**Comment by larssnip** [comment]
OK, nice. I could see from the Viewer of the genome that the > at the start of the FASTA Header-lines is present, which was the error in microseq I mentioned. With the newest version of microseq this should not be there…(silly error introduced in the previous version)


LS
